root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp\\main.exe"  # Ensure output is an .exe file
  cmd = "go build -o tmp/main.exe ."  # Correct build command for Windows
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  delay = 1000
  poll = false
